# Welcome to My Blog!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: liuwei's blog
email: liuweiiii@163.com
description: > # this means to ignore newlines until "baseurl:"
  My blog, for recording my learnning history.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://liuweiii.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  liuweiii

# Build settings
markdown: kramdown
